version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0

jobs:
  build:
    docker:
      - image: level12/python-test-multi
    steps:
      - checkout

      - run:
          name: Debugging info
          command: |
              ls -al
              echo $PATH

      - run:
          name: Install OS tools
          command: |
              python3.12 -m pip install -r requirements/ci.txt
              python3.12 --version
              python3.12 -m nox --version

      - run:
          name: run nox
          command: python3.12 -m nox

      - store_test_results:
          path: ci/test-reports/

      - codecov/upload:
          file: ci/test-reports/tests-3.12.pytests.xml
